version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: backend
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./data:/var/lib/postgresql/data